{{- if .Values.ingress.enable }}
{{- range .Values.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .cert }}
spec:
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ .tlsSecret }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}
---
{{- end }}
{{- end }}
