# Default values for tenant-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: my-nginx

namespace: tenant-a

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


service:
  type: ClusterIP
  port: 80

ingress:
  enable: true

ingresses:
  - name: nginx-ingress
    host: tenant-a.local
    cert: self-signed
    tlsSecret: tls-secret
    serviceName: nginx
    servicePort: 80

networkPolicy:
  enable: true

nodeSelector: {}

tolerations: []

affinity: {}
