apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: spring-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: spring-app
