apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-auth-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "pods"]
    verbs: ["get"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]

