apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector: 
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres
      volumes:
        - name: vault-agent-config
          configMap:
            name: vault-agent-postgres
        - name: vault-secret
          emptyDir: {}
      containers:
        - name: vault-agent                         #Container used as sidecar for vault
          image: hashicorp/vault:1.14
          command: ["vault", "agent", "-config=/etc/vault/vault-agent-postgres.hcl"]
          volumeMounts:                             #mounting shared volumes and placing the cred in them
            - name: vault-agent-config
              mountPath: /etc/vault
            - name: vault-secret
              mountPath: /vault/secrets
  
        - name: postgres
          image: kamalsai33/my-postgres:v1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-superuser-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: vault-secret
              mountPath: /vault/secrets
          command: [ "bash", "-c"]   #uses bash run the following arg as script
          args:                     # reads/export the vault file inside the db container
            - |
              export $(cat /vault/secrets/postgres.env | xargs)
              exec docker-entrypoint.sh postgres   
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
