apiVersion: apps/v1
Kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "Postgres"
  replicas: 1
  selectior: 
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
  spec:
    containers:
      - name: postgres
        image: postgres:13
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: shared-data
            mountPath: /vault/secrets
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data

        env:
          # need to see if i can vault the env varibales or not for stateful set 
