apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saikamal33/Mark-10-Kubernet_repo/tree/main/kube-Mark-10.7
    targetRevision: HEAD
    path: tenant-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

