apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-order
  name: my-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-order
  template:
    metadata:
      labels:
        app: my-order
    spec:
      containers:
      - image: kamalsai33/order-service:v1
        name: order-service
        ports:
        - containerPort: 5002
