apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-order
  name: my-order
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5002
  selector:
    app: my-order
  type: ClusterIP
